language: python
python:
  - "2.7"

branches:
  only:
  - master
  - updateTravisTest

virtualenv:
  system_site_packages: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - boost-latest
    packages:
      - libcppunit-dev
      - libboost1.55-all-dev
      - libboost-python1.55-dev
      - libhdf5-serial-dev
      - cmake
      - g++-4.8

install:
- sudo apt-get update -q -y
- sudo apt-get install python-dev -y
- sudo pip install coveralls numpy
- git clone https://github.com/G-Node/nix.git nix-build
- cd nix-build
- CC=gcc-4.8 CXX=g++-4.8 cmake -DBUILD_TESTING=OFF .
- make
- sudo make install
- cd ..


script:
- CC=gcc-4.8 CXX=g++-4.8 python setup.py install
- coverage run --source=nix setup.py test
- coverage report -m

after_success:
- coveralls
