language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true


install:
- sudo add-apt-repository ppa:gnode/pandora -y
- sudo add-apt-repository ppa:boost-latest/ppa -y
- sudo apt-get update -q -y
- sudo apt-get install python-numpy python-dev libboost-python1.55-dev libboost1.55-all-dev libhdf5-serial-dev libhdf5-dev libhdf5-7
- wget https://launchpad.net/~gnode/+archive/pandora/+files/libnix-dev_0.9.1-1_amd64.deb
- wget https://launchpad.net/~gnode/+archive/pandora/+files/libnix1_0.9.1-1_amd64.deb
- sudo dpkg -i libnix-dev_0.9.1-1_amd64.deb libnix1_0.9.1-1_amd64.deb


script:
- CC=clang CXX=clang++ python setup.py install
- nosetests
