sudo: false

language: python

env:
  - CC=gcc-4.8
  - CXX=g++-4.8
  - NIX_LIBDIR=./nix-build/inst/lib
  - NIX_INCDIR=./nix-build/inst/include

matrix:
  include:
    - python: "2.7_with_system_site_packages"
    - python: "3.4"

branches:
  only:
  - master
  - updateTravisTest

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - boost-latest
    packages:
      - libcppunit-dev
      - libboost1.55-all-dev
      - libhdf5-serial-dev
      - cmake
      - g++-4.8

install:
- pip install coveralls numpy
- git clone https://github.com/G-Node/nix.git nix-build
- cd nix-build
- cmake -DCMAKE_INSTALL_PREFIX=./inst .
- make
- ctest
- make install
- cd ..


script:
- python setup.py build
- coverage run --source=nix setup.py test
- coverage report -m

after_success:
- coveralls
