sudo: required
dist: trusty

language: python

matrix:
    include:
        - python: "2.7_with_system_site_packages"
          env: COVERALLS=1 NIX_LIBDIR="./nix-build/inst/lib" NIX_INCDIR="./nix-build/inst/include"
        - python: "3.4"
          env: NIX_LIBDIR="./nix-build/inst/lib" NIX_INCDIR="./nix-build/inst/include"
        - python: "2.7_with_system_site_packages"
        - python: "3.4"

addons:
  apt:
    packages:
      - cmake
      - libcppunit-dev
      - libhdf5-serial-dev
      - libboost-all-dev

install:
  - export PYVER=${TRAVIS_PYTHON_VERSION:0:1}
  # install dependencies
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      g++ --version;
    fi
  - pip install --upgrade numpy coveralls h5py
  #build NIX
  - if [ -n "$NIX_LIBDIR" ]; then
      git clone https://github.com/G-Node/nix.git nix-build;
      pushd nix-build;
      cmake -DCMAKE_INSTALL_PREFIX=./inst -DBUILD_TESTING=OFF .;
      make;
      make install;
      popd;
    fi

script:
- python setup.py build
- if [ $COVERALLS = 1 ]; then
    coverage${PYVER} run --source=nixio setup.py test && coverage${PYVER} report -m;
  else
    python setup.py test;
  fi;

after_success:
- if [ $COVERALLS = 1 ]; then coveralls; fi;
