version: 1.4.{build}

image: Visual Studio 2017

environment:
  DEPLOY_DIR: deploy


  matrix:
    # Python 3.6 32 bit
    - PYTHON: "C:\\Python36"
    # Python 3.7 32 bit
    - PYTHON: "C:\\Python37"
    # Python 3.6 64 bit
    - PYTHON: "C:\\Python36-x64"
    # Python 3.7 64 bit
    - PYTHON: "C:\\Python37-x64"
      RDP: "no"

init:
  - set PATH=%PYTHON%;%PATH%
  - python -c "import sys; print('Python version is {}'.format(sys.version))"
  - python -m pip install -U pip
  - python -m pip install -U pytest pytest-xdist setuptools wheel

install:
  - cd "%APPVEYOR_BUILD_FOLDER%"
    # install deps automatically
  - python -m pip install .

build_script:
  - python setup.py build

test_script:
  - python setup.py test --addopts "-nauto"

after_test:
  - mkdir "%DEPLOY_DIR%"
  - python setup.py bdist_wheel -d %DEPLOY_DIR%

artifacts:
  - path: $(DEPLOY_DIR)\*
    name: wheels

on_finish:
  - ps: |
      if ($env:RDP -eq "yes") {
          $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }
